version: '3'

services:

  broker:
    build:
      context: ./broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
    - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - broker
    volumes:
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      BROKER_URL: http://broker:80

volumes:
  node_modules: